name: Scan app

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Code scan
    uses: colinsalmcorner/super-approved-workflows/.github/workflows/codeql-scan.yml@main
    with:
      languages: '["csharp"]'
